# © Copyright 2024 - 2026 Transsion Core
# © Copyright 2024 - 2026 Dizzy
# © Copyright 2026 Ave Labs

"""Domain primitive NewTypes for the TCF Bot database layer."""

from __future__ import annotations

from typing import NewType

# ────────────────────────── ID Primitives ───────────────────────── #
# * Distinct names prevent accidentally swapping e.g. chat_id for user_id
# * All are backed by int or str at runtime (zero overhead)

UserId = NewType("UserId", int)
"""Telegram user ID (positive integer)."""

GroupId = NewType("GroupId", int)
"""Telegram supergroup/group chat ID (typically negative integer)."""

ChatId = NewType("ChatId", int)
"""Generic Telegram chat ID; use GroupId when the chat is known to be a group."""

BanId = NewType("BanId", str)
"""Short alphanumeric federation ban identifier, generated by make_short_id()."""
